
(custom-set-variables
  ;; custom-set-variables was added by Custom -- don't edit or cut/paste it!
  ;; Your init file should contain only one such instance.
 '(canlock-password "65b941b580e5929c8ac95266fec4130f3e586b0d")
 '(check-mail-summary-function (quote check-mail-box-summary) t)
 '(desktop-buffers-not-to-save "\\(^nn\\.a[0-9]+\\|\\.log\\|(ftp)\\|^tags\\|^TAGS\\|^=tagging.*\\)$")
 '(ecb-layout-name "left-analyse")
 '(ecb-options-version "2.32")
 '(ecb-windows-width 0.2)
 '(frame-background-mode (quote dark))
 '(gnus-article-loose-mime t)
 '(org-agenda-files (quote ("~/Organizer/JesseDutton.org" "~/Organizer/Notes.org" "~/Organizer/Clearpath.org" "~/Organizer/Personal.org"))))
 
(custom-set-faces
  ;; custom-set-faces was added by Custom -- don't edit or cut/paste it!
  ;; Your init file should contain only one such instance.
 '(default ((t (:background "unspecified-bg" :foreground "unspecified-fg"))))
 '(cperl-array-face ((t (:foreground "yellow"))))
 '(cperl-hash-face ((t (:foreground "wheat"))))
 '(diff-added-face ((t (:inherit diff-changed-face :foreground "green"))))
 '(diff-changed-face ((((type tty pc) (class color) (background dark)) (:foreground "yellow" :slant italic :weight bold))))
 '(diff-context-face ((((class color) (background dark)) (:foreground "white"))))
 '(diff-file-header-face ((((class color) (background dark)) (:foreground "yellow" :weight bold))))
 '(diff-header-face ((nil (:foreground "cyan"))))
 '(diff-removed-face ((t (:inherit diff-changed-face :foreground "red"))))
 '(ecb-default-highlight-face ((((class color) (background dark)) (:background "black" :foreground "yellow" :weight bold))))
 '(erc-action-face ((t (:foreground "dark green" :weight bold))))
 '(erc-command-indicator-face ((t (:foreground "blue" :weight bold))))
 '(erc-current-nick-face ((t (:foreground "gold3" :weight bold))))
 '(erc-keyword-face ((t (:foreground "magenta3" :weight bold))))
 '(erc-nick-default-face ((((class color) (background light)) (:foreground "dodger blue")) (((class color) (background dark)) (:foreground "cyan"))))
 '(erc-notice-face ((((type tty)) (:foreground "black" :weight bold))))
 '(erc-pal-face ((t (:foreground "blue3" :weight bold))))
 '(erc-prompt-face ((t (:background "blue" :foreground "white" :weight bold))))
 '(erc-timestamp-face ((t (:foreground "brown"))))
 '(font-lock-builtin-face ((t (:foreground "brightred"))))
 '(font-lock-comment-face ((t (:italic t :foreground "black" :weight bold))))
 '(font-lock-constant-face ((t (:foreground "red"))))
 '(font-lock-function-name-face ((t (:bold t :foreground "cyan"))))
 '(font-lock-keyword-face ((t (:bold t :foreground "white"))))
 '(font-lock-string-face ((t (:foreground "green"))))
 '(font-lock-type-face ((t (:foreground "brightblue"))))
 '(font-lock-variable-name-face ((t (:foreground "brightyellow"))))
 '(font-lock-warning-face ((((class color) (background dark)) (:foreground "red"))))
 '(gnus-cite-attribution-face ((t (:background "black" :foreground "yellow" :slant italic))))
 '(gnus-cite-face-1 ((nil (:foreground "cyan"))))
 '(gnus-cite-face-2 ((nil (:foreground "blue"))))
 '(gnus-cite-face-3 ((nil (:foreground "magenta"))))
 '(gnus-cite-face-4 ((nil (:foreground "black" :weight bold))))
 '(gnus-cite-face-5 ((((class color) (background dark)) (:foreground "black" :weight bold))))
 '(gnus-group-mail-1-empty-face ((nil (:foreground "magenta"))))
 '(gnus-group-mail-1-face ((t (:foreground "magenta" :weight bold))))
 '(gnus-group-mail-2-empty-face ((nil (:foreground "yellow"))))
 '(gnus-group-mail-2-face ((t (:foreground "yellow" :weight bold))))
 '(gnus-group-mail-3-empty-face ((nil (:foreground "green"))))
 '(gnus-group-mail-3-face ((t (:foreground "green" :weight bold))))
 '(gnus-group-news-1-face ((t (:foreground "magenta" :weight bold))))
 '(gnus-group-news-3-empty-face ((((class color) (background dark)) (:foreground "cyan"))))
 '(gnus-group-news-3-face ((t (:foreground "brightcyan"))))
 '(gnus-header-content-face ((t (:foreground "green" :slant italic))))
 '(gnus-header-from-face ((nil (:foreground "red"))))
 '(gnus-header-name-face ((nil (:foreground "black" :weight bold))))
 '(gnus-header-newsgroups-face ((t (:foreground "blue" :slant italic))))
 '(gnus-header-subject-face ((nil (:foreground "yellow"))))
 '(gnus-signature-face ((t (:foreground "Red"))))
 '(gnus-splash-face ((nil (:foreground "black" :weight bold :weight bold))))
 '(gnus-summary-cancelled-face ((((class color)) (:background "red" :foreground "black"))))
 '(gnus-summary-high-ancient-face ((t (:foreground "brightcyan"))))
 '(gnus-summary-high-read-face ((t (:background "black" :foreground "white" :weight bold))))
 '(gnus-summary-high-ticked-face ((t (:foreground "brightred"))))
 '(gnus-summary-high-undownloaded-face ((t (:bold t :foreground "Lightblue"))))
 '(gnus-summary-high-unread-face ((t (:bold t))))
 '(gnus-summary-low-ancient-face ((t (:foreground "blue"))))
 '(gnus-summary-low-read-face ((t (:background "black" :foreground "black"))))
 '(gnus-summary-low-ticked-face ((t (:foreground "red"))))
 '(gnus-summary-low-undownloaded-face ((t (:foreground "Lightblue"))))
 '(gnus-summary-low-unread-face ((t (:foreground "black" :weight bold))))
 '(gnus-summary-normal-ancient-face ((t (:foreground "cyan"))))
 '(gnus-summary-normal-read-face ((t (:background "black" :foreground "white"))))
 '(gnus-summary-normal-ticked-face ((t (:foreground "red"))))
 '(gnus-summary-normal-undownloaded-face ((t (:foreground "Lightblue"))))
 '(gnus-summary-normal-unread-face ((t (:bold nil))))
 '(gnus-summary-selected-face ((t (:background "brightyellow" :foreground "black" :weight bold))))
 '(header-line ((t (:background "unspecified-bg" :foreground "yellow"))))
 '(highlight ((t (:background "unspecified-bg" :foreground "blue" :weight bold))))
 '(isearch ((t (:foreground "purple4" :background "azure"))))
 '(isearch-lazy-highlight-face ((t (:inherit (quote match) :foreground "yellow"))))
 '(margin-face ((t (:inverse-video t))))
 '(match ((((class color) (background dark)) (:background "black" :foreground "red" :weight bold))))
 '(message-cited-text-face ((t (:foreground "cyan"))))
 '(message-header-cc-face ((t (:foreground "magenta"))))
 '(message-header-name-face ((t (:foreground "black" :weight bold))))
 '(message-header-other-face ((t (:foreground "Green"))))
 '(message-header-subject-face ((t (:foreground "brightyellow"))))
 '(message-header-to-face ((t (:foreground "red" :weight bold))))
 '(message-header-xheader-face ((t (:foreground "brightblue"))))
 '(message-mml-face ((t (:foreground "SpringGreen"))))
 '(message-separator-face ((t (:foreground "yellow"))))
 '(minibuffer-prompt ((t (:background "unspecified-bg" :foreground "yellow" :bold t))))
 '(mode-line ((t (:foreground "white" :background "black" :box (:line-width -1 :style released-button)))))
 '(mode-line-inactive ((t (:inherit mode-line :foreground "black" :weight bold))))
 '(planner-cancelled-task-face ((t (:foreground "magenta" :strike-through t))))
 '(planner-completed-task-face ((t (:foreground "black" :strike-through t))))
 '(planner-in-progress-task-face ((t (:foreground "yellow" :slant oblique))))
 '(region ((t (:inverse-video t :weight bold))))
 '(show-paren-match-face ((t (:foreground "red" :weight bold))))
 '(smerge-markers-face ((((background light)) (:background "black"))))
 '(smerge-mine-face ((((background light)) (:foreground "yellow"))))
 '(smerge-other-face ((((background light)) (:foreground "green" :weight bold))))
 '(tla-archive-name ((((type tty) (class color)) (:foreground "cyan" :weight light))))
 '(tla-modified ((t (:inherit font-lock-function-name-face :foreground "yellow"))))
 '(tla-move ((t (:inherit font-lock-function-name-face :foreground "magenta"))))
 '(w3m-anchor-face ((nil (:foreground "cyan"))))
 '(w3m-arrived-anchor-face ((t (:foreground "indianred4"))))
 '(w3m-form-button-face ((t (:foreground "magenta"))))
 '(w3m-form-face ((t (:foreground "blue" :background "black" :underline nil))))
 '(w3m-header-line-location-content-face ((t (:foreground "yellow4" :background "unspecified-bg"))))
 '(w3m-header-line-location-title-face ((t (:foreground "DarkGoldenrod" :background "unspecified-bg"))))
 '(w3m-tab-background-face ((t (:background "unspecified-bg"))))
 '(w3m-tab-selected-face ((t (:foreground "black" :background "Gray75"))))
 '(w3m-tab-selected-retrieving-face ((t (:foreground "red4" :background "Gray25"))))
 '(w3m-tab-unselected-face ((t (:foreground "black" :background "unspecified-bg" :bold t))))
 '(w3m-tab-unselected-retrieving-face ((t (:foreground "red4" :background "unspecified-bg")))))
